### ISSUE TITLE
Design Mailer

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/openbadges-badges#22]

**Comment by iamjessklein** [comment]
![obb-mailer](https://f.cloud.github.com/assets/535012/1347394/4a64a6e4-36af-11e3-813d-aedae4625539.png)

**Comment by iamjessklein** [comment]
Of course, all the copy here is placeholder. cc/ @megcolek @christensenep

**Comment by iamjessklein** [comment]
Updated:
![obb-mailer-revised](https://f.cloud.github.com/assets/535012/1382342/5dff8caa-3b2d-11e3-9dff-9b092f87cbff.png)

**Comment by threeqube** [comment]
@carlacasilli I can help with copy. Let me know.

**Comment by carlacasilli** [comment]
@threeqube  and @emgollie please take a crack at this. I can't find the mailer copy that I wrote earlier.

**Comment by emgollie** [comment]
SUBJECT LINE:
You've earned the [Badge name] badge! Send it to your Backpack.

HEADER:
Bravo! 
A new Open Badge is yours for the taking

BODY COPY:
Congratulations. You've earned an Open Badge that you can share with your networks.

I want to send this badge to my Mozilla Backpack [http://backpack.openbadges.org].
[Badge Name]
[Badge Description]
Make this badge mine!

FOOTER
Please reach out to us at support@openbadges.org with any questions.
OpenBadges.org | Facebook | Twitter

**Comment by carlacasilli** [comment]
:+1:

**Comment by emgollie** [comment]
Request re: MozFest badge communications via @carlacasilli: Is it possible to have MozFest badge emails (not Open Badges badge emails) CTA (Make this badge mine! >>) go to http://badges.openbadges.org/claim instead of http://badges.openbadges.org/badges? The Open Badges badge explanation and content is confusing when you're hitting it from a MozFest badge.
